### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by caesarisme** [effector/nextjs-legacy#18]
What is an actual status of the project?

After a quick review I have found some points of resistance:

1. When you define babel config SWC is being disabled so you can not use @next/font for example. I assume that if you dont use babel config you will have issue with `sid` is not being set automatically for states. I also assume that usage of babel config is forced by core `effector` library.

2. Even if you deal with disabled SWC, you will face server-rendered HTML and client-side HTML mismatch error on state hydration stage when you use withStart HOC and modify state. The error appears even with the example code provided in Readme.

3. Probably maintainers can provide a working example of usage of effector within next project without using `effector-next` library

**Comment by sergeysova** [comment]
@caesarisme At the moment I strongly recommend to use https://github.com/risenforces/nextjs-effector

Instead of babel you can use https://github.com/effector/swc-plugin

**Comment by caesarisme** [comment]
@sergeysova Thank you for your response. Yes, this makes sense. 
Probably we need a warning in readme in order to not confuse other developers?

**Comment by sergeysova** [comment]
I'm added a note to the readme
